spring:
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        hbm2ddl.auto: none
  messages:
    basename: messages
    fallback-to-system-locale: false
    use-code-as-default-message: true
server:
  servlet:
    session:
      timeout=15m:

---

spring:
  profiles: default
  datasource:
    url: jdbc:h2:mem:market;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
  resources:
    cache:
      period: 0
